include:
  - project: 'gnome/citemplates'
    file: 'flatpak/flatpak-ci-initiative-sdk-extensions.yml'

flatpak:
  image: 'registry.gitlab.gnome.org/gnome/gnome-runtime-images/rust_bundle:master'
  variables:
    BUNDLE: "read-it-later-nightly.flatpak"
    MANIFEST_PATH: "build-aux/com.belmoussaoui.ReadItLaterDevel.json"
    FLATPAK_MODULE: "read-it-later"
    MESON_ARGS: "-Dprofile=development"
    APP_ID: "com.belmoussaoui.ReadItLaterDevel"
    RUNTIME_REPO: "https://nightly.gnome.org/gnome-nightly.flatpakrepo"
  extends: '.flatpak'

# Configure and run rustfmt
# Exits and builds fails if on bad format
rustfmt:
  image: "rust:slim"
  stage: ".pre"
  script:
    - rustup component add rustfmt
    # Ensure our configured files are present now (although they're generated
    # only later), so rustfmt doesn't yell about non-existent or empty files
    - mv -v src/config.rs{.in,}
    - mv -v src/static_resources.rs{.in,}
    - rustc -Vv && cargo -Vv
    - cargo fmt --version
    - cargo fmt --all -- --color=always --check
