include: 'https://gitlab.gnome.org/GNOME/citemplates/raw/master/flatpak/flatpak-ci-initiative-sdk-extensions.yml'
stages:
  - lint
  - test
  - deploy

variables:
    BUNDLE: "contrast-nightly.flatpak"

flatpak:
    image: "registry.gitlab.gnome.org/gnome/gnome-runtime-images/rust_bundle:master"
    extends: '.flatpak'
    variables:
        MANIFEST_PATH: "build-aux/com.belmoussaoui.ReadingListDevel.json"
        FLATPAK_MODULE: "reading-list"
        MESON_ARGS: "-Dprofile=development"
        APP_ID: "com.belmoussaoui.ReadingListDevel"

review:
    dependencies:
        - flatpak
    extends: '.review'

stop_review:
    extends: '.stop_review'

# Configure and run rustfmt
# Exits and builds fails if on bad format
rustfmt:
  image: "rust:slim"
  stage: "lint"
  script:
    - rustup component add rustfmt
    # Create blank versions of our configured files
    # so rustfmt does not yell about non-existent files or completely empty files
    - echo -e "" >> src/config.rs
    - echo -e "" >> src/static_resources.rs
    - rustc -Vv && cargo -Vv
    - cargo fmt --version
    - cargo fmt --all -- --color=always --check

