# Copyright 2019 Bilal Elmoussaoui <bil.elmoussaoui@gmail.com>
# Copyright 2020 Peter Bittner <django@bittner.it>
# Copyright 2021 Alistair Francis <alistair@alistair23.me>
# Copyright 2022 Casper Meijn <casper@meijn.net>
#
# SPDX-License-Identifier: GPL-3.0-or-later

include:
  - project: 'gnome/citemplates'
    file: 'flatpak/flatpak_ci_initiative.yml'

.vars-devel:
  image: 'quay.io/gnome_infrastructure/gnome-runtime-images:gnome-49'
  variables:
    BUNDLE: "read-it-later-nightly.flatpak"
    MANIFEST_PATH: "build-aux/com.belmoussaoui.ReadItLater.Devel.json"
    FLATPAK_MODULE: "read-it-later"
    APP_ID: "com.belmoussaoui.ReadItLater.Devel"
    RUNTIME_REPO: "https://nightly.gnome.org/gnome-nightly.flatpakrepo"

# Build Flatpak for x86_64
flatpak@x86_64:
  extends: ['.flatpak@x86_64', '.vars-devel']

# Build Flatpak for aarch64
flatpak@aarch64:
  extends: ['.flatpak@aarch64', '.vars-devel']

# Configure and run rustfmt
# Exits and builds fails if on bad format
rustfmt:
  image: "rust:slim"
  stage: test
  script:
    - rustup component add rustfmt
    # Create blank versions of our configured files
    # so rustfmt does not yell about non-existent files or completely empty files
    - echo -e "" >> src/config.rs
    - rustc -Vv && cargo -Vv
    - cargo fmt --version
    - cargo fmt --all -- --color=always --check
