[package]
name = "read-it-later"
version = "0.0.2"
authors = ["Bilal Elmoussaoui <bil.elmoussaoui@gmail.com>"]
edition = "2018"

[dependencies]
gtk = { version = "0.8", features = ["v3_22"] }
glib = "0.9"
gio = { version = "0.8", features = ["v2_56"] }
cairo-rs = "0.8"
gdk = "0.12"
gdk-pixbuf = "0.8"
log = "0.4"
libhandy = "0.5"
webkit2gtk = { version = "0.9", features = ["v2_6"] }
gettext-rs= { version = "0.4", features = ["gettext-system"] }
lazy_static = "1.3"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
wallabag-api = { git = "https://github.com/swalladge/wallabag-api.git", rev = "71a77358d7d573102894af591ca082175a6a8a93" }
pretty_env_logger = "0.3"
diesel = { version = "1.4", features = ["sqlite", "r2d2", "chrono"] }
diesel_migrations = {  version = "1.4" , features = ["sqlite"] }
failure = "0.1"
surf = "1.0"
sanitize_html = "0.6"
regex = "1.3"
secret-service = "1.0"
chrono = "0.4"
url = "2.1"
strum = "0.16"
strum_macros = "0.16"
html2pango = "0.3"
tokio = "0.2.0-alpha.6"
rust-crypto = "0.2"
async-std = "1.4"
gtk-macros = { git = "https://gitlab.gnome.org/haecker-felix/gtk-macros.git" }
