# Copyright 2019 Bilal Elmoussaoui <bil.elmoussaoui@gmail.com>
#
# SPDX-License-Identifier: GPL-3.0-or-later

imports_granularity = "Crate"
format_code_in_doc_comments = true
group_imports = "StdExternalCrate"
newline_style = "Unix"
normalize_comments = true
normalize_doc_attributes = true
wrap_comments = true
